name: Build and publish NGINX Plus unprivileged container
on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile.unpriv'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: codygreen/nginxplus:latest
          secrets: |
            "nginx-repo.crt=${{ secrets.NGINX_REPO_CRT }}"
            "nginx-repo.key=${{ secrets.NGINX_REPO_KEY }}"
          file: Dockerfile.plus_nim
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}